import re

stderr = '<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="2"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Get-Help</AV><AI>0</AI><Nil /><PI>-1</PI><PC>0</PC><T>Processing</T><SR>-1</SR><SD>Searching Help for about_Quoting_Rules ...</SD></PR></MS></Obj><Obj S="progress" RefId="3"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Get-Help</AV><AI>0</AI><Nil /><PI>-1</PI><PC>11</PC><T>Processing</T><SR>-1</SR><SD>Searching Help for about_Quoting_Rules ...</SD></PR></MS></Obj><Obj S="progress" RefId="4"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Get-Help</AV><AI>0</AI><Nil /><PI>-1</PI><PC>22</PC><T>Processing</T><SR>-1</SR><SD>Searching Help for about_Quoting_Rules ...</SD></PR></MS></Obj><Obj S="progress" RefId="5"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Get-Help</AV><AI>0</AI><Nil /><PI>-1</PI><PC>100</PC><T>Processing</T><SR>-1</SR><SD>Searching Help for about_Quoting_Rules ...</SD></PR></MS></Obj><S S="Error">Get-Help : Get-Help could not find about_Quoting_Rules in a help file in this session. To download updated help topics _x000D__x000A_</S><S S="Error">type: "Update-Help". To get help online, search for the help topic in the TechNet library at _x000D__x000A_</S><S S="Error">http://go.microsoft.com/fwlink/?LinkID=107116._x000D__x000A_</S><S S="Error">At line:1 char:1_x000D__x000A_</S><S S="Error">+ Get-Help about_Quoting_Rules_x000D__x000A_</S><S S="Error">+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>'

import lxml.etree
tree = lxml.etree.fromstring(stderr)
for s in tree.xpath('//*[local-name()="S"]'):
    def encode_replace(match):
        return unichr(int(match.group(1), 16))
    line = re.sub(r'_x([0-9A-Fa-f]{4})_', encode_replace, s.text)
